services:
  mysql:
    image: mysql:8.4
    container_name: antrian-tiket-mysql
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: antrian_tiket_app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          '127.0.0.1',
          '-ularavel',
          '-ppassword',
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
